version: "3.3"
services:
  app:
    build:
      context: ./
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
    volumes:
      - ./client.session:/app/client.session
      - ./config.ini:/app/config.ini:ro
    restart: on-failure
