version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app

    restart: always
    volumes:
      - ./client.session:/app/client.session
      - ./config.ini:/app/config.ini:ro
